insert into activities (uuid, content, usr_id, stn_id) values ('c486fd7f-a158-43ac-bae0-2834fe8587ac','Naar aanleiding van de nieuwe corona regels zijn wij bij stichting computersnaar weer GESLOTEN dat betekend', get_user_id('admin@computersnaar.nl'), get_section_id('Home'));
insert into activities (uuid, content, usr_id, stn_id, rendering) values ('7dd88d8f-afed-4f48-83f2-4fbe407aac37',E'<h1>Wegens omstandigheden een simpele boodschap.\r\n \r\n Een ieder fijne kerstdagen en een hoopvol 2021.\r\n \r\n Namens Computersnaar \r\n \r\n Frederik</h1>', get_user_id('admin@computersnaar.nl'), get_section_id('Home'), 'background');
insert into activities (uuid, content, usr_id, stn_id) values ('88d8e1a3-b41a-406d-a2fd-9ecf67eda146','', get_user_id('admin@computersnaar.nl'), get_section_id('Home'));
insert into activities (uuid, content, usr_id, stn_id) values ('69391a78-b9bd-4594-b933-263ddb8d79a8',E'deze wil ik er nog op \r\n', get_user_id('peter.kusters@yahoo.com'), get_section_id('Home'));
insert into activities (uuid, content, usr_id, stn_id) values ('4a643c89-095c-4935-bc67-67458584316e',E'<b>Jamulus configuratie</b>\r\nMet Jamulus kun je via het internet samenspelen.\r\n Om dit vlotjes te laten verlopen is het handig als je je instrument kan koppelen met je computer, via USB.\r\n Aangezien ik linux gebruik is dit best een dingetje. Er zijn maar weinig fabrikanten, helaas, die hier support voor bieden. De focus lijkt te liggen op Mac en Windows.\r\n\r\n Op Reddit heb ik een posting gevonden die hierover gaat. Hier worden fabrikanten genoemd die support bieden voor Linux. Erg handig.\r\n\r\n\r\n <a href="https://amp.reddit.com/r/linuxaudio/comments/apgqmj/officially_linux_supported_audio_interfaces/">linux supported audio interfaces</a>\r\n\r\n <a href="https://focusrite.com/en/usb-audio-interface/scarlett/scarlett-4i4">focusrite scarlet 4i4</a>', get_user_id('admin@computersnaar.nl'), get_section_id('Home'));

insert into activities (uuid, content, usr_id, stn_id) values ('dcec311d-09cd-470a-a6bf-81728b35e58d',E'Officieel moment, slinge 10', get_user_id('admin@computersnaar.nl'), get_section_id('Media'));
insert into activities (uuid, content, usr_id, stn_id) values ('992e5b88-ea97-423b-be99-8603d96e6879',E'Ine jammed wat', get_user_id('admin@computersnaar.nl'), get_section_id('Media'));
insert into activities (uuid, content, usr_id, stn_id) values ('09709417-2e08-48ea-af5c-734d2054d6d2',E'Little Dennis live', get_user_id('admin@computersnaar.nl'), get_section_id('Media'));
insert into activities (uuid, content, usr_id, stn_id) values ('bceae9cc-f99f-4abf-8d11-bcc362a3974b',E'Dia voorstelling', get_user_id('admin@computersnaar.nl'), get_section_id('Media'));
insert into activities (uuid, content, usr_id, stn_id) values ('2544bcf3-950e-4da2-8c57-94eac829fd17',E'Camping jam', get_user_id('admin@computersnaar.nl'), get_section_id('Media'));
insert into activities (uuid, content, usr_id, stn_id) values ('954f9629-a890-4baf-bf4a-1cdc32543154',E'', get_user_id('admin@computersnaar.nl'), get_section_id('Media'));
insert into activities (uuid, content, usr_id, stn_id) values ('e843e7bd-1cc5-4014-b407-57728c1064f3',E'', get_user_id('admin@computersnaar.nl'), get_section_id('Media'));

insert into activities (uuid, content, usr_id, stn_id) values ('a1bdfa55-d058-48a8-a1d8-493d0a492e80',E'Voor altijd in onze gedachte\r\n\r\n Yo', get_user_id('admin@computersnaar.nl'), get_section_id('In memoriam'));
insert into activities (uuid, content, usr_id, stn_id) values ('bf761209-d8f8-4295-a185-f424b3268fd6',E'Voor altijd in onze gedachte\r\n\r\n Ruud', get_user_id('admin@computersnaar.nl'), get_section_id('In memoriam'));

insert into activities (uuid, content, usr_id, stn_id) values ('4c94d347-cee7-4954-bdac-b28a796db1ff',E'<h4>Contact</h4>\r\n <b>Stichting Computersnaar</b>\r\n Slinge 10\r\n 3084 EB Rotterdam\r\n <a href="mailto: stics010@gmail.com">stics010@gmail.com</a>\r\n telefoon: <a href="tel:+31625246964">+31 (0)6-25246964</a>\r\n KvK: 60471603\r\n\r\n\r\n <h4>Doelstelling</h4>\r\n <b>Stichting Computersnaar</b> stelt zich op het vlak van cultuur en nieuwe media ten doel om mensen op deze terreinen  in staat te stellen hun talenten te ontdekken en ontplooien.\r\n Speciale aandacht gaat hierbij uit naar de jeugd en nieuwe media.\r\n\r\n De nadruk van de stichting ligt op culturele diversiteit, via muziek en nieuwe media.\r\n Onze Missie is om culturele expressie en interactie op gang te brengen en te ondersteunen.\r\n We willen daarbij graag een stem geven aan hen die vaak niet gehoord worden. We koppelen inspirerende mensen en ideeën\r\n met cultureel beleid, op lokaal gebied en door gebruik van nieuwe media ook wereldwijd.\r\n\r\n <h4>Wat bieden wij</h4>\r\n <ul>\r\n <li>Het ondersteunen en begeleiden van muziek opnames, videoclips,  cd\'s, dvd\'s, flyers/posters en cd covers. </li>\r\n <li>Het inzetten van een website waarop bovenstaande en andere culturele activiteiten kunnen worden bekeken.</li>\r\n <li>Het geven van oriëntatie clinics muziek en video.</li>\r\n <li>Het bieden van een oefenruimte, voor het maken van opnames (muziek studio).</li>\r\n <li> Het beschikbaar stellen van een blue/green screen room.</li>\r\n <li> Het faciliteren van het realiseren van complete muziek producten, videoclips en artwork</li>\r\n </ul>\r\n', get_user_id('admin@computersnaar.nl'), get_section_id('Over ons'));

insert into activities (uuid, content, usr_id, stn_id) values ('4c8ec135-1182-4951-8838-7036f245e324',E'<h4>Team</h4>\r\n <b>Frederik Grootenboer</b>\r\n Voorzitter\r\n\r\n <b>Dennis Grootenboer</b>\r\n Penningmeester\r\n\r\n <b>Peter Kusters</b>\r\n Ondersteunend Lid\r\n <a href="tel: +31625246964">+31 (0)6-25246964</a>\r\n\r\n\r\n', get_user_id('admin@computersnaar.nl'), get_section_id('Team'));

