CREATE TABLE logs
(
    id          integer primary key not null,
    uuid        varchar(255),
    name        varchar(50),
    msg         text,
    args        text,
    levelname   varchar(20),
    levelno     integer,
    pathname    varchar(255),
    filename    varchar(50),
    module      varchar(50),
    exc_info    text,
    exc_text    text,
    stack_info  text,
    lineno      integer,
    funcName    varchar(50),
    created     real,
    msecs       real,
    relativeCreated  real,
    thread           bigint,
    threadName       varchar(50),
    processName      varchar(50),
    process          bigint,
    message          text,
    asctime          varchar(50),
    created_at  timestamp           not null,
    created_by  varchar(45)         not null,
    updated_at  timestamp           not null,
    updated_by  varchar(45)         not null
);